### ISSUE TITLE
Have a CI system in place

### ISSUE THREAD

**Issue by maxfish** [maxfish/gojira2d#30]
Would be nice to start adding some simple tests and to have TravisCI run them

**Comment by maxfish** [comment]
I don't know much about Travis unfortunately. I've added math_test.go and it works locally.
I've created a .travis.yml config file but it looks like it cannot find our packages:
"package gojira2d/pkg/graphics: unrecognized import path "gojira2d/pkg/graphics" (import path does not begin with hostname)"

**Comment by keymone** [comment]
@maxfish i'm pretty sure it's because in travis our checkout is `$GOPATH/src/github.com/maxfish/gojira2d` while locally we develop in `$GOPATH/src/gojira2d`. if i'm right - we should be able to tell travis to checkout into src/gojira2d directly. you could push your stuff into a branch and i'll have a look if you want.

**Comment by maxfish** [comment]
If that's the case we could clone in the 'right' folder, since I didn't see any specific config in all the Travis files I have read.
Anyway everything is on master already

**Comment by maxfish** [comment]
Fixed by #31
